### ISSUE TITLE
Nodejs test failed with jest using js_test rule

### ISSUE THREAD

**Issue by musmanalibaloch** [zenclabs/bazel-javascript#21]
when I run the rule with js_test rule, it throw error which is ```/private/var/tmp/_bazel_root/4e945cef1c29e1fd0fbd9a3422d28c82/external/zenclabs_js/internal/BUILD.bazel:5:1: SkylarkAction external/zenclabs_js
/internal/packages_installed_dir failed (Exit 127)
external/nodejs/bin/node: line 5: external/nodejs/bin/nodejs/bin/node: No such file or directory``` ,
I can't get any useful information about error.Any one can help please. @fwouts

**Comment by musmanalibaloch** [comment]
Whatever rule I run, I get the same error.

**Comment by fwouts** [comment]
Sorry to hear that! What platform are you on? Which version of Bazel do you use?

**Comment by musmanalibaloch** [comment]
Hi just solved the issue, I just created new project, my previous project is complex so I decided to create new project and things seem to work fine now.Thanks 👍

**Comment by fwouts** [comment]
Good to hear. Feel free to re-open if you run into any other issues.
