### ISSUE TITLE
bazel-javascript does not work with other bazel rule

### ISSUE THREAD

**Issue by musmanalibaloch** [zenclabs/bazel-javascript#22]
bazel-javascript rules are not working with other rules, this probably may be because of the bazel rules that you are using has old release(old tag) and the other bazel rules uses the new release.Here is my workspace file 

**workspace(name = "myWorkspace")

local_repository(
    name = "build_bazel_rules_typescript",
    path = "node_modules/@bazel/typescript",
)

git_repository(
    name = "bazel_skylib",
    remote = "https://github.com/bazelbuild/bazel-skylib",
    tag = "0.5.0"
)

git_repository(
  name = "bazel_javascript",
  remote = "https://github.com/zenclabs/bazel-javascript.git",
  tag = "0.0.24",
)

git_repository(
    name = "build_bazel_rules_nodejs",
    remote = "https://github.com/bazelbuild/rules_nodejs.git",
    tag = "0.12.2"
)

git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker",
    tag = "v0.5.1"
)

# Load js rules 
load("@build_bazel_rules_nodejs//:package.bzl", "rules_nodejs_dependencies")
load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories", "npm_install")

rules_nodejs_dependencies()

# Install your declared Node.js dependencies
npm_install(
    name = "npm_deps",
    package_json = "//:package.json",
)

# Download base images, etc.
load("@io_bazel_rules_docker//nodejs:image.bzl", _nodejs_image_repos = "repositories")

_nodejs_image_repos()

# Fetch our Bazel dependencies that aren't distributed on npm
load("@build_bazel_rules_typescript//:package.bzl", "rules_typescript_dependencies")
rules_typescript_dependencies()

# Setup TypeScript toolchain
load("@build_bazel_rules_typescript//:defs.bzl", "ts_setup_workspace")
ts_setup_workspace()

# Point to the package.json file so Bazel can run the package manager for you.
load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories")
node_repositories(package_json = ["//:package.json"])

# Setup Go toolchain
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()

# Setup web testing, choose browsers we can test on
load("@io_bazel_rules_webtesting//web:repositories.bzl", "browser_repositories", "web_test_repositories")

web_test_repositories()
browser_repositories(
    chromium = True,
)

# Pull image from docker 

load(
  "@io_bazel_rules_docker//docker:docker.bzl",
  "docker_repositories",
  "docker_build",
  "docker_pull"
)

docker_repositories()

docker_pull(
    name = "alpine",
    registry = "gcr.io",
    repository = "google-containers/alpine-with-bash",
    tag = "1.0",
)**

**Comment by enriched** [comment]
What kind of error are you getting? I guess I am a little confused because I see you pulling the `bazel_javascript` rules in your WORKSPACE file but then I don't see any usage of those rules.

But on a more general note. I think that it would be great to have better interop with other rules, but till rules_nodejs has some providers for it then I think that it might be a bit hairy.  There are open issues for adding providers to rules_nodejs:

https://github.com/bazelbuild/rules_nodejs/issues/278
https://github.com/bazelbuild/rules_nodejs/issues/57

There is currently a [provider for amd module names](https://github.com/bazelbuild/rules_nodejs/blob/36b68a2e2355e01ddd8b5a4aa44d1df8f7c4322b/internal/js_library/js_library.bzl#L23) but the js_library rule that creates it has documentation that says not to use it.

@fwouts have you gotten these to work with `bazelbuild/rules_typescript`?

**Comment by musmanalibaloch** [comment]
###ERROR
INFO: Analysed target //packages/server/src/tests:test (0 packages loaded).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_usmanbaloch/4e945cef1c29e1fd0fbd9a3422d28c82/external/bazel_javascript/internal/BUILD.bazel:5:1: SkylarkAction external
/bazel_javascript/internal/packages_installed_dir failed (Exit 127)
external/nodejs/bin/node: line 5: external/nodejs/bin/nodejs/bin/node: No such file or directory
Target //packages/server/src/tests:test failed to build

##But
when I change the build_bazel_rules_nodejs version to `0.10.0` test works but other rules do not find the file package.bzl because it does not exists in 0.10.0 and if I change it to current versions which is `0.12.2` it has package.bzl and defs.bzl but defs.bzl has some breaking changes.

**Comment by musmanalibaloch** [comment]
@enriched  I am using rules in BAZEL.build files, its just WORKSPACE file that I copied from.

**Comment by fwouts** [comment]
@musmanalibaloch unfortunately it's not as simple as updating our rules. Something changed in `build_bazel_rules_nodejs`, and I suspect it's a bug. You can follow updates at https://github.com/bazelbuild/rules_nodejs/issues/314.

**Comment by fwouts** [comment]
A quick update: maintainers of the `rules_nodejs` repo have confirmed the bug, and they're working on a fix :)
