### ISSUE TITLE
public_path attr missing in rule web_bundle

### ISSUE THREAD

**Issue by dan-compton** [zenclabs/bazel-javascript#30]
`public_path` is listed as a visible attribute for rule `web_bundle` in README.md.  However, this attribute is not included in the implementation and consequently not carried through to the generated webpack configuration.  See https://github.com/zenclabs/bazel-javascript/blob/master/internal/web_bundle/rule.bzl#L228-L293

I have a branch that fixes this and carries the variable through to the publicPath field in the resultant webpack configuration.  I can issue a PR if you would like.

**Comment by fwouts** [comment]
That'd be great, thank you!

**Comment by fwouts** [comment]
Fixed in #31.
